import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "@/components/header";
import Hero from "@/components/hero";
import Projects from "@/components/projects";
import Footer from "@/components/footer";

import styles from "@/styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stefania Rapisarda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Hero />
        <Projects />
        <Footer />
      </main>
    </>
  );
}
